// Java Exception with keyword "try"
//public class New{
//	public static void main(String[] args) {
//		System.out.println("hiiiiiii");
//	
//	
//	try
//	{
//		System.out.println(10/0);
//	
//	}
//	catch(ArithmeticException e) //Exception handling for Arithmetic Exception 
//	{
//		System.out.println(10/2); //
//	}
//	System.out.println("Hello");
//}
//}

//public class New{
//	public static void main(String[] args) {
//	int[] arr = new int[4];
//	try {
//		System.out.println(arr[4]);
//		System.out.println("Inside");
//	}
//	catch(Exception e)
//	{
//		System.out.println(e);
//	}
//	}
//}